[project]
name = "tool-calling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyter>=1.1.1",
    "openai>=1.97.1",
    "pydantic>=2.11.7",
    "python-pptx>=1.0.2",
    "requests>=2.32.4",
]
